# Default values for kube-rclone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
images:
  container:
    repository: rclone/rclone
    tag: latest
  pullPolicy: IfNotPresent

# imagePullSecrets:

rclone:
  #  remote to mount from rclone config
  remote: "gcache:"
  # mount path for  remote
  path: /mnt/disks/gdrive
  # read only file system for remote (to protect from deletion of files)
  readOnly: true
  # additional arguments for customising rclone
  # mount options can be found here - https://rclone.org/commands/rclone_mount/#options
  additionalArgs:
    - --umask=000
    - --vfs-cache-mode=writes
    - --vfs-cache-min-free-space=5G
    # - --buffer-size=1G
    # - --dir-cache-time=72h
    # - --drive-chunk-size=256M
    # - --log-level=INFO
    # - --vfs-read-chunk-size=128M
    # - --vfs-read-chunk-size-limit=off
  config: |
    [gcache]
    You can use this config to mount Google Drive

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # requests:
  #   cpu: 250m
  #   memory: 1Gi
  # limits:
  #   cpu: 350m
  #   memory: 2Gi

nodeSelector: {}
